# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogCondicionalTwe.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogiConditionalTwe(object):
    def setupUi(self, DialogiConditionalTwe):
        DialogiConditionalTwe.setObjectName("DialogiConditionalTwe")
        DialogiConditionalTwe.resize(400, 150)
        DialogiConditionalTwe.setMinimumSize(QtCore.QSize(400, 150))
        DialogiConditionalTwe.setMaximumSize(QtCore.QSize(400, 150))
        self.centralwidget = QtWidgets.QWidget(DialogiConditionalTwe)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(60, 60))
        self.frame.setMaximumSize(QtCore.QSize(80, 90))
        self.frame.setStyleSheet("background-image: url(:/dialog/estoque/Alert.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.LabelDialogMsg = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.LabelDialogMsg.sizePolicy().hasHeightForWidth())
        self.LabelDialogMsg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(10)
        self.LabelDialogMsg.setFont(font)
        self.LabelDialogMsg.setScaledContents(False)
        self.LabelDialogMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelDialogMsg.setWordWrap(True)
        self.LabelDialogMsg.setObjectName("LabelDialogMsg")
        self.verticalLayout.addWidget(self.splitter)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_2 = QtWidgets.QFrame(self.splitter_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButtonSim = QtWidgets.QPushButton(self.splitter_2)
        self.pushButtonSim.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButtonSim.setObjectName("pushButtonSim")
        self.pushButtonNao = QtWidgets.QPushButton(self.splitter_2)
        self.pushButtonNao.setMaximumSize(QtCore.QSize(93, 28))
        self.pushButtonNao.setObjectName("pushButtonNao")
        self.verticalLayout.addWidget(self.splitter_2)
        DialogiConditionalTwe.setCentralWidget(self.centralwidget)

        self.retranslateUi(DialogiConditionalTwe)
        QtCore.QMetaObject.connectSlotsByName(DialogiConditionalTwe)

    def retranslateUi(self, DialogiConditionalTwe):
        _translate = QtCore.QCoreApplication.translate
        DialogiConditionalTwe.setWindowTitle(_translate("DialogiConditionalTwe", "Dialog"))
        self.LabelDialogMsg.setText(_translate("DialogiConditionalTwe", "CHAVE NÃO CADASTRADA"))
        self.pushButtonSim.setText(_translate("DialogiConditionalTwe", "SIM"))
        self.pushButtonNao.setText(_translate("DialogiConditionalTwe", "NÃO"))
import IconAlert_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogiConditionalTwe = QtWidgets.QMainWindow()
    ui = Ui_DialogiConditionalTwe()
    ui.setupUi(DialogiConditionalTwe)
    DialogiConditionalTwe.show()
    sys.exit(app.exec_())
