# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainLogin(object):
    def setupUi(self, MainLogin):
        MainLogin.setObjectName("MainLogin")
        MainLogin.resize(1458, 609)
        self.centralwidget = QtWidgets.QWidget(MainLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_Backgound = QtWidgets.QFrame(self.centralwidget)
        self.frame_Backgound.setStyleSheet("background-color: rgb(4, 52, 61);")
        self.frame_Backgound.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Backgound.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Backgound.setObjectName("frame_Backgound")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_Backgound)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_topbar = QtWidgets.QFrame(self.frame_Backgound)
        self.frame_topbar.setEnabled(True)
        self.frame_topbar.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_topbar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_topbar.setStyleSheet("background-color: rgb(4, 52, 61);")
        self.frame_topbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_topbar.setObjectName("frame_topbar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_topbar)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_erro = QtWidgets.QFrame(self.frame_topbar)
        self.frame_erro.setMaximumSize(QtCore.QSize(223, 25))
        self.frame_erro.setStyleSheet("background-color: rgb(0, 175, 157);\n"
"border-radius: 6px;")
        self.frame_erro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_erro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_erro.setObjectName("frame_erro")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_erro)
        self.horizontalLayout_3.setContentsMargins(-1, 2, 5, 2)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_erro = QtWidgets.QLabel(self.frame_erro)
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setBold(True)
        font.setWeight(75)
        self.label_erro.setFont(font)
        self.label_erro.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"};")
        self.label_erro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_erro.setObjectName("label_erro")
        self.horizontalLayout_3.addWidget(self.label_erro)
        self.Button_quit = QtWidgets.QPushButton(self.frame_erro)
        self.Button_quit.setMaximumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Button_quit.setFont(font)
        self.Button_quit.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(0, 175, 157);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    cursor: pointer;\n"
"    background-color: rgb(204, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    cursor: pointer;\n"
"    background-color: rgb(134, 0, 0);\n"
"}")
        self.Button_quit.setObjectName("Button_quit")
        self.horizontalLayout_3.addWidget(self.Button_quit)
        self.horizontalLayout_2.addWidget(self.frame_erro)
        self.verticalLayout.addWidget(self.frame_topbar)
        self.frame_backlogin = QtWidgets.QFrame(self.frame_Backgound)
        self.frame_backlogin.setMinimumSize(QtCore.QSize(350, 500))
        self.frame_backlogin.setStyleSheet("background-color: rgb(4, 52, 61);")
        self.frame_backlogin.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_backlogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_backlogin.setObjectName("frame_backlogin")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_backlogin)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_login = QtWidgets.QFrame(self.frame_backlogin)
        self.frame_login.setMaximumSize(QtCore.QSize(300, 500))
        self.frame_login.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.frameUser = QtWidgets.QFrame(self.frame_login)
        self.frameUser.setGeometry(QtCore.QRect(37, 200, 223, 39))
        self.frameUser.setStyleSheet("QFrame {\n"
"background-color: rgb(245, 245, 245);\n"
"border-radius:4px;\n"
"padding: 2px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"border: 1px solid;\n"
"border-color: rgb(0, 53, 62);\n"
"}\n"
"QFrame:pressed {\n"
"border: inset;\n"
"}\n"
"")
        self.frameUser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUser.setObjectName("frameUser")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameUser)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.frameUser)
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border: not;")
        self.lineEdit.setMaxLength(18)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.frameUser_2 = QtWidgets.QFrame(self.frame_login)
        self.frameUser_2.setGeometry(QtCore.QRect(37, 260, 223, 39))
        self.frameUser_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(245, 245, 245);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    border: 1px solid;\n"
"    border-color: rgb(0, 53, 62);\n"
"}")
        self.frameUser_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameUser_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameUser_2.setObjectName("frameUser_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameUser_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frameUser_2)
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border: not;")
        self.lineEdit_3.setMaxLength(16)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.ENTER = QtWidgets.QPushButton(self.frame_login)
        self.ENTER.setGeometry(QtCore.QRect(37, 360, 223, 45))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ENTER.setFont(font)
        self.ENTER.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    \n"
"    background-color: rgb(0, 175, 157);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    color: rgb(4, 52, 61);\n"
"    cursor: pointer;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(0, 140, 124);\n"
"}\n"
"")
        self.ENTER.setObjectName("ENTER")
        self.frame = QtWidgets.QFrame(self.frame_login)
        self.frame.setGeometry(QtCore.QRect(36, 100, 226, 68))
        self.frame.setStyleSheet("background-image: url(:/logo/LOGO.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame_login)
        self.label.setGeometry(QtCore.QRect(20, 420, 261, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setStyleSheet("color: rgb(208, 208, 208);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.frame_login)
        self.verticalLayout.addWidget(self.frame_backlogin)
        self.frame_Downbar = QtWidgets.QFrame(self.frame_Backgound)
        self.frame_Downbar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_Downbar.setStyleSheet("background-color: rgb(4, 52, 61);")
        self.frame_Downbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Downbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Downbar.setObjectName("frame_Downbar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_Downbar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.frame_Downbar)
        self.verticalLayout_3.addWidget(self.frame_Backgound)
        MainLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainLogin)
        QtCore.QMetaObject.connectSlotsByName(MainLogin)

    def retranslateUi(self, MainLogin):
        _translate = QtCore.QCoreApplication.translate
        MainLogin.setWindowTitle(_translate("MainLogin", "COMUNICATION TECHNOLOGICAL SOLUTION"))
        self.label_erro.setText(_translate("MainLogin", "TextLabel"))
        self.Button_quit.setText(_translate("MainLogin", "X"))
        self.lineEdit.setPlaceholderText(_translate("MainLogin", "Usuario"))
        self.lineEdit_3.setPlaceholderText(_translate("MainLogin", "Senha"))
        self.ENTER.setText(_translate("MainLogin", "ENTRAR"))
        self.label.setText(_translate("MainLogin", "© 2022 Comunication Technological Solution"))
import iconesLogin_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainLogin = QtWidgets.QMainWindow()
    ui = Ui_MainLogin()
    ui.setupUi(MainLogin)
    MainLogin.show()
    sys.exit(app.exec_())
