# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opCell.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_opCell(object):
    def setupUi(self, opCell):
        opCell.setObjectName("opCell")
        opCell.resize(600, 400)
        opCell.setMinimumSize(QtCore.QSize(600, 400))
        opCell.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(opCell)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color: rgb(0, 161, 148);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageOpImei = QtWidgets.QWidget()
        self.pageOpImei.setObjectName("pageOpImei")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageOpImei)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.pageOpImei)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_2.setStyleSheet("background-image: url(:/button/imei.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.splitter_9 = QtWidgets.QSplitter(self.pageOpImei)
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.label_10 = QtWidgets.QLabel(self.splitter_9)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label = QtWidgets.QLabel(self.splitter_9)
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.opLineImei_2 = QtWidgets.QLineEdit(self.splitter_9)
        self.opLineImei_2.setMinimumSize(QtCore.QSize(406, 32))
        self.opLineImei_2.setMaximumSize(QtCore.QSize(406, 32))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(9)
        self.opLineImei_2.setFont(font)
        self.opLineImei_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px;\n"
"border-radius: 10px")
        self.opLineImei_2.setText("")
        self.opLineImei_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.opLineImei_2.setPlaceholderText("")
        self.opLineImei_2.setObjectName("opLineImei_2")
        self.label_15 = QtWidgets.QLabel(self.splitter_9)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.splitter_9)
        self.splitter_4 = QtWidgets.QSplitter(self.pageOpImei)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_8 = QtWidgets.QLabel(self.splitter_4)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_20 = QtWidgets.QLabel(self.splitter_4)
        self.label_20.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setObjectName("label_20")
        self.opLineImei = QtWidgets.QLineEdit(self.splitter_4)
        self.opLineImei.setMinimumSize(QtCore.QSize(406, 32))
        self.opLineImei.setMaximumSize(QtCore.QSize(406, 32))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(9)
        self.opLineImei.setFont(font)
        self.opLineImei.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px;\n"
"border-radius: 10px")
        self.opLineImei.setText("")
        self.opLineImei.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.opLineImei.setPlaceholderText("")
        self.opLineImei.setObjectName("opLineImei")
        self.label_9 = QtWidgets.QLabel(self.splitter_4)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.splitter_4)
        self.splitter_3 = QtWidgets.QSplitter(self.pageOpImei)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_6 = QtWidgets.QLabel(self.splitter_3)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.opButtonImei = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opButtonImei.sizePolicy().hasHeightForWidth())
        self.opButtonImei.setSizePolicy(sizePolicy)
        self.opButtonImei.setMinimumSize(QtCore.QSize(0, 37))
        self.opButtonImei.setMaximumSize(QtCore.QSize(115, 37))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.opButtonImei.setFont(font)
        self.opButtonImei.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.opButtonImei.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 53, 62);\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 73, 85);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 64, 74);\n"
"    color: rgb(98, 98, 98);\n"
"}\n"
"")
        self.opButtonImei.setObjectName("opButtonImei")
        self.label_7 = QtWidgets.QLabel(self.splitter_3)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.splitter_3)
        self.opLabelImei = QtWidgets.QLabel(self.pageOpImei)
        self.opLabelImei.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.opLabelImei.setFont(font)
        self.opLabelImei.setStyleSheet("color: rgb(255, 255, 255)")
        self.opLabelImei.setText("")
        self.opLabelImei.setAlignment(QtCore.Qt.AlignCenter)
        self.opLabelImei.setObjectName("opLabelImei")
        self.verticalLayout_2.addWidget(self.opLabelImei)
        self.stackedWidget.addWidget(self.pageOpImei)
        self.pageOpEmail = QtWidgets.QWidget()
        self.pageOpEmail.setObjectName("pageOpEmail")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageOpEmail)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.pageOpEmail)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_4.setStyleSheet("background-image: url(:/button/email.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5.addWidget(self.frame_4)
        self.splitter_8 = QtWidgets.QSplitter(self.pageOpEmail)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.label_18 = QtWidgets.QLabel(self.splitter_8)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.opLineEmail = QtWidgets.QLineEdit(self.splitter_8)
        self.opLineEmail.setMinimumSize(QtCore.QSize(406, 32))
        self.opLineEmail.setMaximumSize(QtCore.QSize(406, 32))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(9)
        self.opLineEmail.setFont(font)
        self.opLineEmail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px;\n"
"border-radius: 10px")
        self.opLineEmail.setText("")
        self.opLineEmail.setAlignment(QtCore.Qt.AlignCenter)
        self.opLineEmail.setObjectName("opLineEmail")
        self.label_19 = QtWidgets.QLabel(self.splitter_8)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.splitter_8)
        self.splitter_7 = QtWidgets.QSplitter(self.pageOpEmail)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.label_16 = QtWidgets.QLabel(self.splitter_7)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.opButtonEmail = QtWidgets.QPushButton(self.splitter_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opButtonEmail.sizePolicy().hasHeightForWidth())
        self.opButtonEmail.setSizePolicy(sizePolicy)
        self.opButtonEmail.setMinimumSize(QtCore.QSize(0, 37))
        self.opButtonEmail.setMaximumSize(QtCore.QSize(115, 37))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.opButtonEmail.setFont(font)
        self.opButtonEmail.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.opButtonEmail.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 53, 62);\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 73, 85);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 64, 74);\n"
"    color: rgb(98, 98, 98);\n"
"}\n"
"")
        self.opButtonEmail.setObjectName("opButtonEmail")
        self.label_17 = QtWidgets.QLabel(self.splitter_7)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.splitter_7)
        self.opLabelEmail = QtWidgets.QLabel(self.pageOpEmail)
        self.opLabelEmail.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.opLabelEmail.setFont(font)
        self.opLabelEmail.setStyleSheet("color: rgb(255, 255, 255)")
        self.opLabelEmail.setText("")
        self.opLabelEmail.setAlignment(QtCore.Qt.AlignCenter)
        self.opLabelEmail.setObjectName("opLabelEmail")
        self.verticalLayout_5.addWidget(self.opLabelEmail)
        self.stackedWidget.addWidget(self.pageOpEmail)
        self.pageOpUser = QtWidgets.QWidget()
        self.pageOpUser.setObjectName("pageOpUser")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageOpUser)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.pageOpUser)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame.setStyleSheet("background-image: url(:/button/user.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3.addWidget(self.frame)
        self.splitter = QtWidgets.QSplitter(self.pageOpUser)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.opLineUser = QtWidgets.QLineEdit(self.splitter)
        self.opLineUser.setMinimumSize(QtCore.QSize(406, 32))
        self.opLineUser.setMaximumSize(QtCore.QSize(406, 32))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(9)
        self.opLineUser.setFont(font)
        self.opLineUser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px;\n"
"border-radius: 10px")
        self.opLineUser.setText("")
        self.opLineUser.setAlignment(QtCore.Qt.AlignCenter)
        self.opLineUser.setObjectName("opLineUser")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.splitter)
        self.splitter_2 = QtWidgets.QSplitter(self.pageOpUser)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_4 = QtWidgets.QLabel(self.splitter_2)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.opButtonUser = QtWidgets.QPushButton(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opButtonUser.sizePolicy().hasHeightForWidth())
        self.opButtonUser.setSizePolicy(sizePolicy)
        self.opButtonUser.setMinimumSize(QtCore.QSize(0, 37))
        self.opButtonUser.setMaximumSize(QtCore.QSize(115, 37))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.opButtonUser.setFont(font)
        self.opButtonUser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.opButtonUser.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 53, 62);\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 73, 85);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 64, 74);\n"
"    color: rgb(98, 98, 98);\n"
"}\n"
"")
        self.opButtonUser.setObjectName("opButtonUser")
        self.label_5 = QtWidgets.QLabel(self.splitter_2)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.opLabelUser = QtWidgets.QLabel(self.pageOpUser)
        self.opLabelUser.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.opLabelUser.setFont(font)
        self.opLabelUser.setStyleSheet("color: rgb(255, 255, 255)")
        self.opLabelUser.setText("")
        self.opLabelUser.setAlignment(QtCore.Qt.AlignCenter)
        self.opLabelUser.setObjectName("opLabelUser")
        self.verticalLayout_3.addWidget(self.opLabelUser)
        self.stackedWidget.addWidget(self.pageOpUser)
        self.pageOpLocal = QtWidgets.QWidget()
        self.pageOpLocal.setObjectName("pageOpLocal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageOpLocal)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.pageOpLocal)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_3.setStyleSheet("background-image: url(:/button/local.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4.addWidget(self.frame_3)
        self.splitter_6 = QtWidgets.QSplitter(self.pageOpLocal)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.label_13 = QtWidgets.QLabel(self.splitter_6)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.opBoxLocal = QtWidgets.QComboBox(self.splitter_6)
        self.opBoxLocal.setMinimumSize(QtCore.QSize(406, 32))
        self.opBoxLocal.setMaximumSize(QtCore.QSize(406, 32))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.opBoxLocal.setFont(font)
        self.opBoxLocal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.opBoxLocal.setAutoFillBackground(False)
        self.opBoxLocal.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.opBoxLocal.setObjectName("opBoxLocal")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.setItemText(0, "")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.opBoxLocal.addItem("")
        self.label_14 = QtWidgets.QLabel(self.splitter_6)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.splitter_6)
        self.splitter_5 = QtWidgets.QSplitter(self.pageOpLocal)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_11 = QtWidgets.QLabel(self.splitter_5)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.opButtonLocal = QtWidgets.QPushButton(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opButtonLocal.sizePolicy().hasHeightForWidth())
        self.opButtonLocal.setSizePolicy(sizePolicy)
        self.opButtonLocal.setMinimumSize(QtCore.QSize(0, 37))
        self.opButtonLocal.setMaximumSize(QtCore.QSize(115, 37))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.opButtonLocal.setFont(font)
        self.opButtonLocal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.opButtonLocal.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 53, 62);\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 73, 85);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 64, 74);\n"
"    color: rgb(98, 98, 98);\n"
"}\n"
"")
        self.opButtonLocal.setObjectName("opButtonLocal")
        self.label_12 = QtWidgets.QLabel(self.splitter_5)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.splitter_5)
        self.oplabelLocal = QtWidgets.QLabel(self.pageOpLocal)
        self.oplabelLocal.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.oplabelLocal.setFont(font)
        self.oplabelLocal.setStyleSheet("color: rgb(255, 255, 255)")
        self.oplabelLocal.setAlignment(QtCore.Qt.AlignCenter)
        self.oplabelLocal.setObjectName("oplabelLocal")
        self.verticalLayout_4.addWidget(self.oplabelLocal)
        self.stackedWidget.addWidget(self.pageOpLocal)
        self.verticalLayout.addWidget(self.stackedWidget)
        opCell.setCentralWidget(self.centralwidget)

        self.retranslateUi(opCell)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(opCell)

    def retranslateUi(self, opCell):
        _translate = QtCore.QCoreApplication.translate
        opCell.setWindowTitle(_translate("opCell", "MainWindow"))
        self.label.setText(_translate("opCell", "IMEI 1:"))
        self.label_20.setText(_translate("opCell", "IMEI 2:"))
        self.opButtonImei.setText(_translate("opCell", "COMFIRMAR"))
        self.opLineEmail.setPlaceholderText(_translate("opCell", "TND98-PM9HM-QB6BR-KFGX9-2YT4C"))
        self.opButtonEmail.setText(_translate("opCell", "PESQUISAR"))
        self.opLineUser.setPlaceholderText(_translate("opCell", "SIDE HENRIQUE DA SILVA PAES LANDIM"))
        self.opButtonUser.setText(_translate("opCell", "PESQUISAR"))
        self.opBoxLocal.setItemText(1, _translate("opCell", "ESTOQUE TI"))
        self.opBoxLocal.setItemText(2, _translate("opCell", "ESTOQUE UAD"))
        self.opBoxLocal.setItemText(3, _translate("opCell", "U. G. Pessoas"))
        self.opBoxLocal.setItemText(4, _translate("opCell", "U. A. Rural"))
        self.opBoxLocal.setItemText(5, _translate("opCell", "U. Cadastro"))
        self.opBoxLocal.setItemText(6, _translate("opCell", "U. Cobrança"))
        self.opBoxLocal.setItemText(7, _translate("opCell", "Conselho ADM"))
        self.opBoxLocal.setItemText(8, _translate("opCell", "U. Controladoria"))
        self.opBoxLocal.setItemText(9, _translate("opCell", "U. Crédito"))
        self.opBoxLocal.setItemText(10, _translate("opCell", "D. Operacional"))
        self.opBoxLocal.setItemText(11, _translate("opCell", "U. Financeiro"))
        self.opBoxLocal.setItemText(12, _translate("opCell", "U. G. Riscos"))
        self.opBoxLocal.setItemText(13, _translate("opCell", "U. P. Serviços"))
        self.opBoxLocal.setItemText(14, _translate("opCell", "U. Retaguarda"))
        self.opBoxLocal.setItemText(15, _translate("opCell", "S. Executiva"))
        self.opBoxLocal.setItemText(16, _translate("opCell", "U. Tecnologia"))
        self.opBoxLocal.setItemText(17, _translate("opCell", "D. Administrativa"))
        self.opBoxLocal.setItemText(18, _translate("opCell", "G. Operacional"))
        self.opBoxLocal.setItemText(19, _translate("opCell", "G. Administrativa"))
        self.opBoxLocal.setItemText(20, _translate("opCell", "G. Comercial"))
        self.opBoxLocal.setItemText(21, _translate("opCell", "Recepção"))
        self.opBoxLocal.setItemText(22, _translate("opCell", "PA - Planaltina"))
        self.opBoxLocal.setItemText(23, _translate("opCell", "PA - São João"))
        self.opBoxLocal.setItemText(24, _translate("opCell", "PA - SIA"))
        self.opBoxLocal.setItemText(25, _translate("opCell", "PA - Águas Claras"))
        self.opBoxLocal.setItemText(26, _translate("opCell", "PA -Pad/DF"))
        self.opBoxLocal.setItemText(27, _translate("opCell", "PA - Vicente Pires"))
        self.opBoxLocal.setItemText(28, _translate("opCell", "PA - Formosa"))
        self.opBoxLocal.setItemText(29, _translate("opCell", "PA - São Sebastião"))
        self.opBoxLocal.setItemText(30, _translate("opCell", "PA- Digital"))
        self.opButtonLocal.setText(_translate("opCell", "CONFIRMAR"))
        self.oplabelLocal.setText(_translate("opCell", "(U. G.) Unidade de Gestão   |   (U. A.) Unidade de Assessoramento   |   (U.)  Unidade   |   (D.) Diretoria   |  \n"
" (U. P.) Unidade Produtos   |   (S.) Secretaria   |   (G.) Gerencia   |   (PA) Ponto de Atendimento "))

import buttonNote_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    opCell = QtWidgets.QMainWindow()
    ui = Ui_opCell()
    ui.setupUi(opCell)
    opCell.show()
    sys.exit(app.exec_())

