# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Positive.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Positive(object):
    def setupUi(self, Positive):
        Positive.setObjectName("Positive")
        Positive.resize(400, 150)
        Positive.setMinimumSize(QtCore.QSize(400, 150))
        Positive.setMaximumSize(QtCore.QSize(400, 150))
        self.verticalLayout = QtWidgets.QVBoxLayout(Positive)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(Positive)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setMinimumSize(QtCore.QSize(60, 60))
        self.frame.setMaximumSize(QtCore.QSize(80, 90))
        self.frame.setAcceptDrops(False)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-image: url(:/dialog/estoque/positiv.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;")
        self.frame.setInputMethodHints(QtCore.Qt.ImhNone)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.LabelDialog = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LabelDialog.setFont(font)
        self.LabelDialog.setStyleSheet("color: rgb(0, 161, 148);")
        self.LabelDialog.setScaledContents(False)
        self.LabelDialog.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelDialog.setWordWrap(True)
        self.LabelDialog.setObjectName("LabelDialog")
        self.verticalLayout.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(Positive)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Positive)
        self.buttonBox.accepted.connect(Positive.accept) # type: ignore
        self.buttonBox.rejected.connect(Positive.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Positive)

    def retranslateUi(self, Positive):
        _translate = QtCore.QCoreApplication.translate
        Positive.setWindowTitle(_translate("Positive", "Dialog"))
        self.LabelDialog.setText(_translate("Positive", "CADASTRADO COM SUCESSO"))

import IconAlert_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Positive = QtWidgets.QDialog()
    ui = Ui_Positive()
    ui.setupUi(Positive)
    Positive.show()
    sys.exit(app.exec_())
